Experimentation of models for anomaly detection

In [1]:
import mlflow
import pandas as pd
import joblib
from sklearn.ensemble import IsolationForest
from pathlib import Path

In [2]:
base_path = Path("C:/Users/acer/Desktop/Vangaurd")

data = pd.read_csv(base_path / "data/processed/processed_train_FD001.csv")

print(data.shape)
print(data.columns.tolist)

(20631, 47)
<bound method IndexOpsMixin.tolist of Index(['op_settings1', 'op_settings2', 'op_settings3', 'sensor2', 'sensor3',
       'sensor4', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12',
       'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21',
       'raw_RUL', 'sensor2_mean', 'sensor2_std', 'sensor3_mean', 'sensor3_std',
       'sensor4_mean', 'sensor4_std', 'sensor7_mean', 'sensor7_std',
       'sensor8_mean', 'sensor8_std', 'sensor9_mean', 'sensor9_std',
       'sensor11_mean', 'sensor11_std', 'sensor12_mean', 'sensor12_std',
       'sensor13_mean', 'sensor13_std', 'sensor14_mean', 'sensor14_std',
       'sensor15_mean', 'sensor15_std', 'sensor17_mean', 'sensor17_std',
       'sensor20_mean', 'sensor20_std', 'sensor21_mean', 'sensor21_std',
       'RUL'],
      dtype='object')>

In [3]:
print(data.head())
print(data.columns.tolist())

   op_settings1  op_settings2  op_settings3   sensor2   sensor3   sensor4  \
0      0.459770      0.166667           0.0  0.183735  0.406802  0.309757
1      0.609195      0.250000           0.0  0.283133  0.453019  0.352633
2      0.252874      0.750000           0.0  0.343373  0.369523  0.370527
3      0.540230      0.500000           0.0  0.343373  0.256159  0.331195
4      0.390805      0.333333           0.0  0.349398  0.257467  0.404625

    sensor7   sensor8   sensor9  sensor11  ...  sensor14_std  sensor15_mean  \
0  0.726248  0.242424  0.109755  0.369048  ...      0.000000       0.463943
1  0.628019  0.212121  0.100242  0.380952  ...      0.257354       0.495930
2  0.710145  0.272727  0.140043  0.250000  ...      0.189759       0.482320
3  0.740741  0.318182  0.124518  0.166667  ...      0.155735       0.411021
4  0.668277  0.242424  0.149960  0.255952  ...      0.135338       0.431904

   sensor15_std  sensor17_mean  sensor17_std  sensor20_mean  sensor20_std  \
0      0.000000       0.303030      0.000000       0.747899      0.000000
1      0.132258       0.303030      0.000000       0.711885      0.130435
2      0.116172       0.202020      0.408248       0.679872      0.169323
3      0.427568       0.227273      0.353553       0.642857      0.234642
4      0.394651       0.272727      0.387298       0.625450      0.226338

   sensor21_mean  sensor21_std  RUL
0       0.753677      0.000000  125
1       0.758565      0.017365  125
2       0.703945      0.237961  125
3       0.692415      0.202745  125
4       0.698461      0.178837  125

[5 rows x 47 columns]
['op_settings1', 'op_settings2', 'op_settings3', 'sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21', 'raw_RUL', 'sensor2_mean', 'sensor2_std', 'sensor3_mean', 'sensor3_std', 'sensor4_mean', 'sensor4_std', 'sensor7_mean', 'sensor7_std', 'sensor8_mean', 'sensor8_std', 'sensor9_mean', 'sensor9_std', 'sensor11_mean', 'sensor11_std', 'sensor12_mean', 'sensor12_std', 'sensor13_mean', 'sensor13_std', 'sensor14_mean', 'sensor14_std', 'sensor15_mean', 'sensor15_std', 'sensor17_mean', 'sensor17_std', 'sensor20_mean', 'sensor20_std', 'sensor21_mean', 'sensor21_std', 'RUL']

In [4]:
columns = ['unit_number' , 'time', 'op_settings1' , 'op_settings2' , 'op_settings3'] + [f'sensor{i}' for i in range(1,22)]

original_data = pd.read_csv(f"C:\\Users\\acer\\Desktop\\Vangaurd\\data\\raw\\files\\train_FD001.txt", sep = r"\s+", header = None, names = columns) 

original_data

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor12,sensor13,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [5]:
data['unit_number'] = original_data['unit_number']
data['time'] = original_data['time']

data

,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,...,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std,RUL,unit_number,time
0,0.459770,0.166667,0.0,0.183735,0.406802,0.309757,0.726248,0.242424,0.109755,0.369048,...,0.000000,0.303030,0.000000,0.747899,0.000000,0.753677,0.000000,125,1,1
1,0.609195,0.250000,0.0,0.283133,0.453019,0.352633,0.628019,0.212121,0.100242,0.380952,...,0.132258,0.303030,0.000000,0.711885,0.130435,0.758565,0.017365,125,1,2
2,0.252874,0.750000,0.0,0.343373,0.369523,0.370527,0.710145,0.272727,0.140043,0.250000,...,0.116172,0.202020,0.408248,0.679872,0.169323,0.703945,0.237961,125,1,3
3,0.540230,0.500000,0.0,0.343373,0.256159,0.331195,0.740741,0.318182,0.124518,0.166667,...,0.427568,0.227273,0.353553,0.642857,0.234642,0.692415,0.202745,125,1,4
4,0.390805,0.333333,0.0,0.349398,0.257467,0.404625,0.668277,0.242424,0.149960,0.255952,...,0.394651,0.272727,0.387298,0.625450,0.226338,0.698461,0.178837,125,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,0.477011,0.250000,0.0,0.686747,0.587312,0.782917,0.254428,0.439394,0.196491,0.726190,...,0.351904,0.856061,0.401887,0.064226,0.377914,0.120218,0.406119,4,100,196
20627,0.408046,0.083333,0.0,0.701807,0.729453,0.866475,0.162641,0.500000,0.194651,0.708333,...,0.352050,0.856061,0.401887,0.046218,0.390729,0.133416,0.393656,3,100,197
20628,0.522989,0.500000,0.0,0.665663,0.684979,0.775321,0.175523,0.515152,0.198196,0.738095,...,0.396068,0.878788,0.438298,0.039616,0.387600,0.102397,0.436494,2,100,198
20629,0.436782,0.750000,0.0,0.608434,0.746021,0.747468,0.133655,0.530303,0.233285,0.916667,...,0.406169,0.871212,0.442407,0.019808,0.390448,0.091293,0.434224,1,100,199
20630,0.316092,0.083333,0.0,0.795181,0.639634,0.842167,0.151369,0.545455,0.178363,0.803571,...,0.406757,0.878788,0.438298,0.009604,0.389201,0.071920,0.407873,0,100,200

In [6]:
x = data[data['time'] <= 30].copy()

print(x.columns.tolist())

['op_settings1', 'op_settings2', 'op_settings3', 'sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21', 'raw_RUL', 'sensor2_mean', 'sensor2_std', 'sensor3_mean', 'sensor3_std', 'sensor4_mean', 'sensor4_std', 'sensor7_mean', 'sensor7_std', 'sensor8_mean', 'sensor8_std', 'sensor9_mean', 'sensor9_std', 'sensor11_mean', 'sensor11_std', 'sensor12_mean', 'sensor12_std', 'sensor13_mean', 'sensor13_std', 'sensor14_mean', 'sensor14_std', 'sensor15_mean', 'sensor15_std', 'sensor17_mean', 'sensor17_std', 'sensor20_mean', 'sensor20_std', 'sensor21_mean', 'sensor21_std', 'RUL', 'unit_number', 'time']

In [7]:
x

,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,...,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std,RUL,unit_number,time
0,0.459770,0.166667,0.0,0.183735,0.406802,0.309757,0.726248,0.242424,0.109755,0.369048,...,0.000000,0.303030,0.000000,0.747899,0.000000,0.753677,0.000000,125,1,1
1,0.609195,0.250000,0.0,0.283133,0.453019,0.352633,0.628019,0.212121,0.100242,0.380952,...,0.132258,0.303030,0.000000,0.711885,0.130435,0.758565,0.017365,125,1,2
2,0.252874,0.750000,0.0,0.343373,0.369523,0.370527,0.710145,0.272727,0.140043,0.250000,...,0.116172,0.202020,0.408248,0.679872,0.169323,0.703945,0.237961,125,1,3
3,0.540230,0.500000,0.0,0.343373,0.256159,0.331195,0.740741,0.318182,0.124518,0.166667,...,0.427568,0.227273,0.353553,0.642857,0.234642,0.692415,0.202745,125,1,4
4,0.390805,0.333333,0.0,0.349398,0.257467,0.404625,0.668277,0.242424,0.149960,0.255952,...,0.394651,0.272727,0.387298,0.625450,0.226338,0.698461,0.178837,125,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20456,0.482759,0.500000,0.0,0.349398,0.479834,0.456111,0.661836,0.333333,0.160774,0.392857,...,0.281984,0.325758,0.401887,0.564226,0.294901,0.587329,0.356611,125,100,26
20457,0.511494,0.750000,0.0,0.388554,0.361674,0.392134,0.661836,0.242424,0.172081,0.303571,...,0.276127,0.318182,0.395701,0.560024,0.288967,0.604246,0.339660,125,100,27
20458,0.500000,0.750000,0.0,0.388554,0.326793,0.376435,0.719807,0.303030,0.165440,0.238095,...,0.287948,0.340909,0.411592,0.549820,0.290208,0.619070,0.317083,125,100,28
20459,0.609195,0.583333,0.0,0.430723,0.350992,0.472991,0.479871,0.212121,0.133402,0.285714,...,0.276740,0.348485,0.415173,0.543818,0.292342,0.620994,0.313954,125,100,29
20460,0.448276,0.250000,0.0,0.358434,0.339002,0.274983,0.681159,0.272727,0.178363,0.309524,...,0.282316,0.348485,0.415173,0.533013,0.265201,0.612673,0.300247,125,100,30

In [8]:
ex_cols = ['unit_number' , 'time' , 'raw_RUL' , 'RUL']
x = x.drop(columns = ex_cols)
x

,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,...,sensor14_mean,sensor14_std,sensor15_mean,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std
0,0.459770,0.166667,0.0,0.183735,0.406802,0.309757,0.726248,0.242424,0.109755,0.369048,...,0.207823,0.000000,0.463943,0.000000,0.303030,0.000000,0.747899,0.000000,0.753677,0.000000
1,0.609195,0.250000,0.0,0.283133,0.453019,0.352633,0.628019,0.212121,0.100242,0.380952,...,0.183722,0.257354,0.495930,0.132258,0.303030,0.000000,0.711885,0.130435,0.758565,0.017365
2,0.252874,0.750000,0.0,0.343373,0.369523,0.370527,0.710145,0.272727,0.140043,0.250000,...,0.179610,0.189759,0.482320,0.116172,0.202020,0.408248,0.679872,0.169323,0.703945,0.237961
3,0.540230,0.500000,0.0,0.343373,0.256159,0.331195,0.740741,0.318182,0.124518,0.166667,...,0.178567,0.155735,0.411021,0.427568,0.227273,0.353553,0.642857,0.234642,0.692415,0.202745
4,0.390805,0.333333,0.0,0.349398,0.257467,0.404625,0.668277,0.242424,0.149960,0.255952,...,0.177901,0.135338,0.431904,0.394651,0.272727,0.387298,0.625450,0.226338,0.698461,0.178837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20456,0.482759,0.500000,0.0,0.349398,0.479834,0.456111,0.661836,0.333333,0.160774,0.392857,...,0.227881,0.170812,0.479026,0.281984,0.325758,0.401887,0.564226,0.294901,0.587329,0.356611
20457,0.511494,0.750000,0.0,0.388554,0.361674,0.392134,0.661836,0.242424,0.172081,0.303571,...,0.228355,0.169195,0.483655,0.276127,0.318182,0.395701,0.560024,0.288967,0.604246,0.339660
20458,0.500000,0.750000,0.0,0.388554,0.326793,0.376435,0.719807,0.303030,0.165440,0.238095,...,0.230163,0.168780,0.490235,0.287948,0.340909,0.411592,0.549820,0.290208,0.619070,0.317083
20459,0.609195,0.583333,0.0,0.430723,0.350992,0.472991,0.479871,0.212121,0.133402,0.285714,...,0.231684,0.161618,0.484748,0.276740,0.348485,0.415173,0.543818,0.292342,0.620994,0.313954
20460,0.448276,0.250000,0.0,0.358434,0.339002,0.274983,0.681159,0.272727,0.178363,0.309524,...,0.230968,0.160511,0.478714,0.282316,0.348485,0.415173,0.533013,0.265201,0.612673,0.300247

In [9]:
print(x.columns.tolist())

['op_settings1', 'op_settings2', 'op_settings3', 'sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21', 'sensor2_mean', 'sensor2_std', 'sensor3_mean', 'sensor3_std', 'sensor4_mean', 'sensor4_std', 'sensor7_mean', 'sensor7_std', 'sensor8_mean', 'sensor8_std', 'sensor9_mean', 'sensor9_std', 'sensor11_mean', 'sensor11_std', 'sensor12_mean', 'sensor12_std', 'sensor13_mean', 'sensor13_std', 'sensor14_mean', 'sensor14_std', 'sensor15_mean', 'sensor15_std', 'sensor17_mean', 'sensor17_std', 'sensor20_mean', 'sensor20_std', 'sensor21_mean', 'sensor21_std']

In [10]:
x = x.reset_index(drop = True)

In [11]:

base_path = Path("C:/Users/acer/Desktop/Vangaurd")

mlflow.set_experiment("Vanguard_Anomaly_Detection")

with mlflow.start_run(run_name="Isolation Forest"):
    
    mlflow.log_param("model_type", "IsolationForest")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("contamination", 0.05)
    mlflow.log_param("random_state", 42)
    
    isolation_forest = IsolationForest(
        n_estimators=100,
        contamination=0.05,
        random_state=42
    )
    isolation_forest.fit(x)
    
    x_full = data.drop(columns=ex_cols)
    x_full = x_full.reset_index(drop=True)
    
    decision_score = isolation_forest.decision_function(x_full)
    
    data['anomaly_score'] = decision_score
    
    healthy_score = decision_score[data['time'] <= 30]
    mean_healthy = healthy_score.mean()
    
    max_time = data.groupby('unit_number')['time'].transform('max')
    fail_score = decision_score[data['time'] > (max_time * 0.7)]
    mean_fail = fail_score.mean() if len(fail_score) > 0 else 0
    
    mlflow.log_metric("mean_healthy_score", mean_healthy)
    mlflow.log_metric("mean_failing_score", mean_fail)
    mlflow.log_metric("score_difference", mean_healthy - mean_fail)
    mlflow.log_metric("score_ratio", mean_fail / mean_healthy if mean_healthy != 0 else 0)
    
    models_dir = base_path / 'models'
    models_dir.mkdir(exist_ok=True)
    
    model_path = models_dir / 'anomaly_detector_if.joblib'
    joblib.dump(isolation_forest, model_path)
    mlflow.log_artifact(str(model_path))
   
    feature_names_path = models_dir / "feature_names.txt"
    with open(feature_names_path, "w") as f:
        f.write("\n".join(x.columns.tolist()))
    mlflow.log_artifact(str(feature_names_path))
    
    print(" MLflow run completed successfully!")

print(f"\n Results:")
print(f"   Mean healthy score: {mean_healthy:.4f}")
print(f"   Mean failing score: {mean_fail:.4f}")
print(f"   Score difference: {mean_healthy - mean_fail:.4f}")

2026/06/05 15:38:20 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

 MLflow run completed successfully!

 Results:
   Mean healthy score: 0.0760
   Mean failing score: -0.0581
   Score difference: 0.1342