In [23]:
import pandas as pd
import numpy as np

In [7]:
columns = ['unit_number' , 'time', 'op_settings1' , 'op_settings2' , 'op_settings3'] + [f'sensor{i}' for i in range(1,22)]

data = pd.read_csv(f"C:\\Users\\acer\\Desktop\\Vangaurd\\data\\raw\\files\\train_FD001.txt", sep = r"\s+", header = None, names = columns) 

data

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor12,sensor13,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

Calculating raw RUL and piece-wise  RUL for each engine

In [8]:
data['max_cycle'] = data.groupby('unit_number')['time'].transform('max') 

data

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor13,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,max_cycle
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,192
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,192
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,192
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,192
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735,200
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594,200
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333,200
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640,200
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522,200

In [9]:
data['raw_RUL'] = data['max_cycle'] - data['time']

data['RUL'] = data['raw_RUL'].clip(upper = 125)

data

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,max_cycle,raw_RUL,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8.4195,0.03,392,2388,100.0,39.06,23.4190,192,191,125
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8.4318,0.03,392,2388,100.0,39.00,23.4236,192,190,125
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8.4178,0.03,390,2388,100.0,38.95,23.3442,192,189,125
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8.3682,0.03,392,2388,100.0,38.88,23.3739,192,188,125
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8.4294,0.03,393,2388,100.0,38.90,23.4044,192,187,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,8.4956,0.03,397,2388,100.0,38.49,22.9735,200,4,4
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,8.5139,0.03,395,2388,100.0,38.30,23.1594,200,3,3
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,8.5646,0.03,398,2388,100.0,38.44,22.9333,200,2,2
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,8.5389,0.03,395,2388,100.0,38.29,23.0640,200,1,1
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,8.5036,0.03,396,2388,100.0,38.37,23.0522,200,0,0

In [10]:
data = data.drop(columns = ['max_cycle'])

data

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,raw_RUL,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,191,125
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,190,125
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,189,125
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,188,125
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,187,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735,4,4
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594,3,3
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333,2,2
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640,1,1
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522,0,0

Choosing sensors that actually correlates with the degradation of machinery

In [14]:
sensors = [f'sensor{i}' for i in range(1,22)]
for sensor in sensors:
    deviation = data[sensor].std()
    print(f'{sensor} - {deviation}')

sensor1 - 0.0
sensor2 - 0.5000532700606232
sensor3 - 6.131149519690819
sensor4 - 9.000604780543714
sensor5 - 5.329199674912836e-15
sensor6 - 0.0013889849127073114
sensor7 - 0.8850922576634073
sensor8 - 0.07098547889092417
sensor9 - 22.082879525066232
sensor10 - 0.0
sensor11 - 0.2670873986396848
sensor12 - 0.7375533922097114
sensor13 - 0.07191891569857814
sensor14 - 19.076175975953106
sensor15 - 0.03750503795196652
sensor16 - 3.469531038354711e-18
sensor17 - 1.548763024614299
sensor18 - 0.0
sensor19 - 0.0
sensor20 - 0.18074642787366083
sensor21 - 0.10825087474491234

In [ ]:
#Sensors with zero or negligible standard deviation.
sensors_to_remove = ['sensor1', 'sensor5', 'sensor6', 'sensor10', 'sensor16', 'sensor18', 'sensor19']

data = data.drop(columns = sensors_to_remove)

data

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,...,sensor11,sensor12,sensor13,sensor14,sensor15,sensor17,sensor20,sensor21,raw_RUL,RUL
0,1,1,-0.0007,-0.0004,100.0,641.82,1589.70,1400.60,554.36,2388.06,...,47.47,521.66,2388.02,8138.62,8.4195,392,39.06,23.4190,191,125
1,1,2,0.0019,-0.0003,100.0,642.15,1591.82,1403.14,553.75,2388.04,...,47.49,522.28,2388.07,8131.49,8.4318,392,39.00,23.4236,190,125
2,1,3,-0.0043,0.0003,100.0,642.35,1587.99,1404.20,554.26,2388.08,...,47.27,522.42,2388.03,8133.23,8.4178,390,38.95,23.3442,189,125
3,1,4,0.0007,0.0000,100.0,642.35,1582.79,1401.87,554.45,2388.11,...,47.13,522.86,2388.08,8133.83,8.3682,392,38.88,23.3739,188,125
4,1,5,-0.0019,-0.0002,100.0,642.37,1582.85,1406.22,554.00,2388.06,...,47.28,522.19,2388.04,8133.80,8.4294,393,38.90,23.4044,187,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,643.49,1597.98,1428.63,551.43,2388.19,...,48.07,519.49,2388.26,8137.60,8.4956,397,38.49,22.9735,4,4
20627,100,197,-0.0016,-0.0005,100.0,643.54,1604.50,1433.58,550.86,2388.23,...,48.04,519.68,2388.22,8136.50,8.5139,395,38.30,23.1594,3,3
20628,100,198,0.0004,0.0000,100.0,643.42,1602.46,1428.18,550.94,2388.24,...,48.09,520.01,2388.24,8141.05,8.5646,398,38.44,22.9333,2,2
20629,100,199,-0.0011,0.0003,100.0,643.23,1605.26,1426.53,550.68,2388.25,...,48.39,519.67,2388.23,8139.29,8.5389,395,38.29,23.0640,1,1
20630,100,200,-0.0032,-0.0005,100.0,643.85,1600.38,1432.14,550.79,2388.26,...,48.20,519.30,2388.26,8137.33,8.5036,396,38.37,23.0522,0,0

In [17]:
print(data.columns)

Index(['unit_number', 'time', 'op_settings1', 'op_settings2', 'op_settings3',
       'sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor9',
       'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17',
       'sensor20', 'sensor21', 'raw_RUL', 'RUL'],
      dtype='str')

Calculating rolling window averages and standard deviation

In [18]:
imp_sensors = ['sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21']

for sensor in imp_sensors:
    mean = data.groupby('unit_number')[sensor].transform( lambda x: x.rolling(window = 20, min_periods = 1).mean() )
    data[f'{sensor}_mean'] = mean

    std = data.groupby('unit_number')[sensor].transform( lambda x: x.rolling(window = 20, min_periods = 1).std() )
    data[f'{sensor}_std'] = std

data.head()

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,...,sensor14_mean,sensor14_std,sensor15_mean,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std
0,1,1,-0.0007,-0.0004,100.0,641.82,1589.70,1400.60,554.36,2388.06,...,8138.620000,NaN,8.419500,NaN,392.000000,NaN,39.060000,NaN,23.419000,NaN
1,1,2,0.0019,-0.0003,100.0,642.15,1591.82,1403.14,553.75,2388.04,...,8135.055000,5.041671,8.425650,0.008697,392.000000,0.000000,39.030000,0.042426,23.421300,0.003253
2,1,3,-0.0043,0.0003,100.0,642.35,1587.99,1404.20,554.26,2388.08,...,8134.446667,3.717450,8.423033,0.007640,391.333333,1.154701,39.003333,0.055076,23.395600,0.044573
3,1,4,0.0007,0.0000,100.0,642.35,1582.79,1401.87,554.45,2388.11,...,8134.292500,3.050906,8.409325,0.028117,391.500000,1.000000,38.972500,0.076322,23.390175,0.037977
4,1,5,-0.0019,-0.0002,100.0,642.37,1582.85,1406.22,554.00,2388.06,...,8134.194000,2.651326,8.413340,0.025953,391.800000,1.095445,38.958000,0.073621,23.393020,0.033498

In [20]:
data = data.fillna(0)
data.head()

,unit_number,time,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,...,sensor14_mean,sensor14_std,sensor15_mean,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std
0,1,1,-0.0007,-0.0004,100.0,641.82,1589.70,1400.60,554.36,2388.06,...,8138.620000,0.000000,8.419500,0.000000,392.000000,0.000000,39.060000,0.000000,23.419000,0.000000
1,1,2,0.0019,-0.0003,100.0,642.15,1591.82,1403.14,553.75,2388.04,...,8135.055000,5.041671,8.425650,0.008697,392.000000,0.000000,39.030000,0.042426,23.421300,0.003253
2,1,3,-0.0043,0.0003,100.0,642.35,1587.99,1404.20,554.26,2388.08,...,8134.446667,3.717450,8.423033,0.007640,391.333333,1.154701,39.003333,0.055076,23.395600,0.044573
3,1,4,0.0007,0.0000,100.0,642.35,1582.79,1401.87,554.45,2388.11,...,8134.292500,3.050906,8.409325,0.028117,391.500000,1.000000,38.972500,0.076322,23.390175,0.037977
4,1,5,-0.0019,-0.0002,100.0,642.37,1582.85,1406.22,554.00,2388.06,...,8134.194000,2.651326,8.413340,0.025953,391.800000,1.095445,38.958000,0.073621,23.393020,0.033498

Feature scaling and fitting feature scaler

In [22]:
ex_cols = ['unit_number', 'time', 'RUL']

X = data.drop(columns=ex_cols)

Y = data['RUL']

print(X.columns.tolist())

['op_settings1', 'op_settings2', 'op_settings3', 'sensor2', 'sensor3', 'sensor4', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21', 'raw_RUL', 'sensor2_mean', 'sensor2_std', 'sensor3_mean', 'sensor3_std', 'sensor4_mean', 'sensor4_std', 'sensor7_mean', 'sensor7_std', 'sensor8_mean', 'sensor8_std', 'sensor9_mean', 'sensor9_std', 'sensor11_mean', 'sensor11_std', 'sensor12_mean', 'sensor12_std', 'sensor13_mean', 'sensor13_std', 'sensor14_mean', 'sensor14_std', 'sensor15_mean', 'sensor15_std', 'sensor17_mean', 'sensor17_std', 'sensor20_mean', 'sensor20_std', 'sensor21_mean', 'sensor21_std']

In [25]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_array = scaler.fit_transform(X)

scaled_x = pd.DataFrame(x_array, columns = X.columns, index = X.index)

scaled_x

,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,...,sensor14_mean,sensor14_std,sensor15_mean,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std
0,0.459770,0.166667,0.0,0.183735,0.406802,0.309757,0.726248,0.242424,0.109755,0.369048,...,0.207823,0.000000,0.463943,0.000000,0.303030,0.000000,0.747899,0.000000,0.753677,0.000000
1,0.609195,0.250000,0.0,0.283133,0.453019,0.352633,0.628019,0.212121,0.100242,0.380952,...,0.183722,0.257354,0.495930,0.132258,0.303030,0.000000,0.711885,0.130435,0.758565,0.017365
2,0.252874,0.750000,0.0,0.343373,0.369523,0.370527,0.710145,0.272727,0.140043,0.250000,...,0.179610,0.189759,0.482320,0.116172,0.202020,0.408248,0.679872,0.169323,0.703945,0.237961
3,0.540230,0.500000,0.0,0.343373,0.256159,0.331195,0.740741,0.318182,0.124518,0.166667,...,0.178567,0.155735,0.411021,0.427568,0.227273,0.353553,0.642857,0.234642,0.692415,0.202745
4,0.390805,0.333333,0.0,0.349398,0.257467,0.404625,0.668277,0.242424,0.149960,0.255952,...,0.177901,0.135338,0.431904,0.394651,0.272727,0.387298,0.625450,0.226338,0.698461,0.178837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,0.477011,0.250000,0.0,0.686747,0.587312,0.782917,0.254428,0.439394,0.196491,0.726190,...,0.224292,0.101154,0.916834,0.351904,0.856061,0.401887,0.064226,0.377914,0.120218,0.406119
20627,0.408046,0.083333,0.0,0.701807,0.729453,0.866475,0.162641,0.500000,0.194651,0.708333,...,0.222111,0.110913,0.916990,0.352050,0.856061,0.401887,0.046218,0.390729,0.133416,0.393656
20628,0.522989,0.500000,0.0,0.665663,0.684979,0.775321,0.175523,0.515152,0.198196,0.738095,...,0.221841,0.110182,0.937014,0.396068,0.878788,0.438298,0.039616,0.387600,0.102397,0.436494
20629,0.436782,0.750000,0.0,0.608434,0.746021,0.747468,0.133655,0.530303,0.233285,0.916667,...,0.222081,0.108601,0.941461,0.406169,0.871212,0.442407,0.019808,0.390448,0.091293,0.434224
20630,0.316092,0.083333,0.0,0.795181,0.639634,0.842167,0.151369,0.545455,0.178363,0.803571,...,0.221523,0.113755,0.938496,0.406757,0.878788,0.438298,0.009604,0.389201,0.071920,0.407873

In [29]:
import joblib
from pathlib import Path

models_path = f"C:\\Users\\acer\\Desktop\\Vangaurd\\models"
joblib.dump(scaler, models_path + '\\scaler.pkl')

['C:\\Users\\acer\\Desktop\\Vangaurd\\models\\scaler.pkl']

In [30]:
processed = Path("C:/Users/acer/Desktop/Vangaurd/data/processed")

processed_data = scaled_x.copy()
processed_data['RUL'] = Y

output_path = processed / 'processed_train_FD001.csv'
processed_data.to_csv(output_path, index = False)

processed_data

,op_settings1,op_settings2,op_settings3,sensor2,sensor3,sensor4,sensor7,sensor8,sensor9,sensor11,...,sensor14_std,sensor15_mean,sensor15_std,sensor17_mean,sensor17_std,sensor20_mean,sensor20_std,sensor21_mean,sensor21_std,RUL
0,0.459770,0.166667,0.0,0.183735,0.406802,0.309757,0.726248,0.242424,0.109755,0.369048,...,0.000000,0.463943,0.000000,0.303030,0.000000,0.747899,0.000000,0.753677,0.000000,125
1,0.609195,0.250000,0.0,0.283133,0.453019,0.352633,0.628019,0.212121,0.100242,0.380952,...,0.257354,0.495930,0.132258,0.303030,0.000000,0.711885,0.130435,0.758565,0.017365,125
2,0.252874,0.750000,0.0,0.343373,0.369523,0.370527,0.710145,0.272727,0.140043,0.250000,...,0.189759,0.482320,0.116172,0.202020,0.408248,0.679872,0.169323,0.703945,0.237961,125
3,0.540230,0.500000,0.0,0.343373,0.256159,0.331195,0.740741,0.318182,0.124518,0.166667,...,0.155735,0.411021,0.427568,0.227273,0.353553,0.642857,0.234642,0.692415,0.202745,125
4,0.390805,0.333333,0.0,0.349398,0.257467,0.404625,0.668277,0.242424,0.149960,0.255952,...,0.135338,0.431904,0.394651,0.272727,0.387298,0.625450,0.226338,0.698461,0.178837,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,0.477011,0.250000,0.0,0.686747,0.587312,0.782917,0.254428,0.439394,0.196491,0.726190,...,0.101154,0.916834,0.351904,0.856061,0.401887,0.064226,0.377914,0.120218,0.406119,4
20627,0.408046,0.083333,0.0,0.701807,0.729453,0.866475,0.162641,0.500000,0.194651,0.708333,...,0.110913,0.916990,0.352050,0.856061,0.401887,0.046218,0.390729,0.133416,0.393656,3
20628,0.522989,0.500000,0.0,0.665663,0.684979,0.775321,0.175523,0.515152,0.198196,0.738095,...,0.110182,0.937014,0.396068,0.878788,0.438298,0.039616,0.387600,0.102397,0.436494,2
20629,0.436782,0.750000,0.0,0.608434,0.746021,0.747468,0.133655,0.530303,0.233285,0.916667,...,0.108601,0.941461,0.406169,0.871212,0.442407,0.019808,0.390448,0.091293,0.434224,1
20630,0.316092,0.083333,0.0,0.795181,0.639634,0.842167,0.151369,0.545455,0.178363,0.803571,...,0.113755,0.938496,0.406757,0.878788,0.438298,0.009604,0.389201,0.071920,0.407873,0

In [31]:
print(processed_data.isnull().sum().sum())

0

In [33]:
print(scaled_x.max().max())
print(scaled_x.min().min())

1.0
0.0